image: homeassistant/home-assistant

pipelines:
  pull-requests:
    feature/*:
      - step:
          size: 1x
          script:
            - echo 'test pipeline!'
          trigger: automatic
          name: Test
