
# configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include customize.yaml

# access externally via the internet
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.3

# mobile apps
mobile_app:

# google assistant
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include service-account.json
  report_state: true

# text to speach
tts:
  - platform: google_translate

# influxdb/grafana
influxdb:
  username: !secret influx_username
  password: !secret influx_password

# overseerr
overseerr:
  host: !secret overseerr_host
  port: !secret overseerr_port
  api_key: !secret overseerr_api_key
  scan_interval: 600

# merged entities
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
zone: !include zones.yaml
input_boolean: !include_dir_merge_named input-booleans/
input_select: !include_dir_merge_named input-select/
device_tracker: !include_dir_merge_list trackers/
notify: !include notify.yaml
