
# configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

frontend:
  themes: !include_dir_merge_named themes

# access externally via the internet
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.3

# mobile apps
mobile_app:

# spotify
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# google assistant
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include service-account.json
  report_state: true

# text to speech (google translate)
tts:
  - platform: google_translate
    base_url: https://alderleyhassio.duckdns.org:8123

# network speeds
speedtestdotnet:

# weather
weather:
  - platform: darksky
    api_key: !secret dark_sky_api

# proxmox-ve
proxmoxve:
  - host: !secret proxmox_ip
    username: !secret proxmox_user
    password: !secret proxmox_pass
    verify_ssl: false
    nodes:
      - node: !secret proxmox_node
        vms:
          - !secret proxmox_vm_one
          - !secret proxmox_vm_two
          - !secret proxmox_vm_three
          - !secret proxmox_vm_four

# influxdb/grafana
influxdb:
  username: !secret influx_username
  password: !secret influx_password

# merged entities
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors/
zone: !include zones.yaml
input_boolean: !include_dir_merge_named input-booleans/
input_select: !include_dir_merge_named input-select/
device_tracker: !include_dir_merge_list trackers/
notify: !include notify.yaml
