# owntracks battery levels - oneplus6t
- platform: mqtt
  state_topic: owntracks/mqtt/oneplus6t
  name: OnePlus6t Battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery

# owntracks connectivity - oneplus6t
- platform: mqtt
  state_topic: owntracks/mqtt/oneplus6t
  name: OnePlus6t Connectivity
  value_template: '{{ value_json.conn }}'

# owntracks gps accuracy - oneplus6t
- platform: mqtt
  state_topic: owntracks/mqtt/oneplus6t
  name: OnePlus6t GPS Accuracy
  unit_of_measurement: "m"
  value_template: '{{ value_json.acc }}'

# owntracks altitude - oneplus6t
- platform: mqtt
  state_topic: owntracks/mqtt/oneplus6t
  name: OnePlus6t Altitude
  unit_of_measurement: "m"
  value_template: '{{ value_json.alt }}'

# owntracks battery levels - s21
- platform: mqtt
  state_topic: owntracks/mqtt/s21
  name: S21 Battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
  device_class: battery

# owntracks connectivity - s21
- platform: mqtt
  state_topic: owntracks/mqtt/s21
  name: S21 Connectivity
  value_template: '{{ value_json.conn }}'

# owntracks gps accuracy - s21
- platform: mqtt
  state_topic: owntracks/mqtt/s21
  name: S21 GPS Accuracy
  unit_of_measurement: "m"
  value_template: '{{ value_json.acc }}'

# owntracks altitude - s21
- platform: mqtt
  state_topic: owntracks/mqtt/s21
  name: S21 Altitude
  unit_of_measurement: "m"
  value_template: '{{ value_json.alt }}'
